#!/usr/bin/env node

/**
 * DevLog 생성 스크립트
 *
 * OpenAI API를 사용하여 일일 DevLog를 생성하고
 * Discord webhook으로 알림을 전송합니다.
 */

const OpenAI = require('openai');
const fs = require('fs');
const path = require('path');

// CLI 인자 파싱
function parseArgs() {
  const args = process.argv.slice(2);
  const parsed = {};

  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].substring(2);
      const value = args[i + 1];
      parsed[key] = value;
      i++;
    }
  }

  return parsed;
}

// Discord webhook 전송
// Note: 현재는 GitHub Actions workflow에서 Discord 알림을 처리합니다.
// 이 함수는 독립 실행이나 로컬 테스트에 사용할 수 있습니다.
async function sendDiscordNotification(webhookUrl, devlog, date, commitCount, user, prUrl) {
  if (!webhookUrl) {
    console.log('⚠️ Discord webhook not configured');
    return;
  }

  try {
    // DevLog 내용에서 주요 작업 추출 (## 🎯 주요 작업 내용 섹션)
    const mainWorkMatch = devlog.match(/## 🎯 주요 작업 내용\s+([\s\S]*?)(?=\n##|$)/);
    let mainWorkSummary = '작업 내역을 확인하세요.';

    if (mainWorkMatch) {
      const mainWorkContent = mainWorkMatch[1].trim();
      // 처음 500자만 사용
      mainWorkSummary = mainWorkContent.substring(0, 500);
      if (mainWorkContent.length > 500) {
        mainWorkSummary += '...';
      }
    }

    const payload = {
      username: 'DevLog Bot 📝',
      embeds: [
        {
          title: `📝 DevLog Generated: ${date}`,
          description: mainWorkSummary,
          color: 5814783, // Blue color
          url: prUrl || undefined,
          fields: [
            {
              name: '📅 Date',
              value: date,
              inline: true
            },
            {
              name: '👤 Author',
              value: user || 'Unknown',
              inline: true
            },
            {
              name: '📊 Commits',
              value: `${commitCount}개`,
              inline: true
            }
          ],
          footer: {
            text: 'Generated by OpenAI GPT-4 via GitHub Actions'
          },
          timestamp: new Date().toISOString()
        }
      ]
    };

    console.log('📤 Sending Discord notification...');

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (response.ok) {
      console.log('✅ Discord notification sent successfully');
    } else {
      const errorText = await response.text();
      console.error('❌ Discord notification failed:', response.status, errorText);
    }
  } catch (error) {
    console.error('❌ Error sending Discord notification:', error.message);
  }
}

// OpenAI로 DevLog 생성
async function generateDevLog(commits, date, user) {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error('OPENAI_API_KEY environment variable is not set');
  }

  const openai = new OpenAI({
    apiKey: apiKey
  });

  // 커밋 정보를 텍스트로 변환
  const commitsText = commits.map((commit, idx) => {
    return `${idx + 1}. [${commit.hash.substring(0, 7)}] ${commit.message}
   Author: ${commit.author}
   Date: ${commit.date}
   ${commit.body ? 'Details: ' + commit.body : ''}`;
  }).join('\n\n');

  const prompt = `다음은 ${date} 날짜의 Git 커밋 내역입니다.

개발자: ${user}
커밋 수: ${commits.length}

## 커밋 목록

${commitsText}

---

## 요청사항

위 커밋 내역을 분석하여 **Daily Development Log (DevLog)**를 한국어로 작성해주세요.

### 형식

\`\`\`markdown
# DevLog - ${date}

## 📅 작업 일자
${date}

## 👤 작업자
${user}

## 📊 작업 통계
- 총 커밋: ${commits.length}개
- 주요 작업: [요약]

## 🎯 주요 작업 내용

### 1. [작업 카테고리]
- 작업 내용 요약
- 주요 변경사항
- 의도 및 목적

### 2. [작업 카테고리]
- ...

## 💡 특이사항
- 중요한 변경사항
- 주의할 점
- 다음 작업 예정

## 📝 커밋 상세

[커밋별 상세 내역 - 원본 메시지 포함]
\`\`\`

### 작성 규칙
1. 커밋 메시지를 분석하여 작업을 카테고리별로 그룹화
2. 각 작업의 의도와 목적을 명확히 설명
3. 기술적인 세부사항도 포함
4. 전문적이고 이해하기 쉬운 문체 사용
5. 다음 작업자가 읽고 바로 이해할 수 있도록 작성

커밋 메시지만 보고 작성하되, 개발 맥락을 파악하여 의미 있는 DevLog를 만들어주세요.`;

  console.log('🤖 Calling OpenAI API...');

  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        {
          role: 'system',
          content: '당신은 전문 개발자이자 기술 문서 작성자입니다. Git 커밋 내역을 분석하여 명확하고 유용한 DevLog를 작성합니다.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 2000
    });

    const devlog = completion.choices[0].message.content;

    console.log('✅ DevLog generated successfully');
    console.log(`📊 Tokens used: ${completion.usage.total_tokens}`);

    return devlog;
  } catch (error) {
    console.error('❌ OpenAI API error:', error.message);
    throw error;
  }
}

// 메인 함수
async function main() {
  try {
    const args = parseArgs();

    console.log('📝 DevLog Generation Started');
    console.log('Arguments:', args);

    const commits = JSON.parse(args.commits || '[]');
    const date = args.date;
    const user = args.user || 'unknown';

    if (commits.length === 0) {
      console.log('⚠️  No commits found. Skipping DevLog generation.');
      process.exit(0);
    }

    console.log(`📅 Date: ${date}`);
    console.log(`👤 User: ${user}`);
    console.log(`📊 Commits: ${commits.length}`);

    // DevLog 생성
    const devlog = await generateDevLog(commits, date, user);

    // 파일로 저장
    const outputPath = path.join(__dirname, 'devlog_output.md');
    fs.writeFileSync(outputPath, devlog, 'utf-8');

    console.log(`✅ DevLog saved to: ${outputPath}`);

    console.log('🎉 DevLog generation completed successfully');
    console.log('📌 Discord notification will be sent by GitHub Actions workflow');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

// 스크립트 실행
main();
