YiSan Project Documentation: UHttpNetworkSystem Class Reference
UHttpNetworkSystem Class Reference
#include <UHttpNetworkSystem.h>
Public Member Functions
DEFINE_SUBSYSTEM_GETTER_INLINE (UHttpNetworkSystem)
virtual void Initialize (FSubsystemCollectionBase &Collection) override
virtual void Deinitialize () override
void RequestHealth (FResponseHealthDelegate InDelegate)
void RequestHelpChat (const FRequestHelpChat &RequestData, FResponseHelpChatDelegate InDelegate)
Member Function Documentation
DEFINE_SUBSYSTEM_GETTER_INLINE()
UHttpNetworkSystem::DEFINE_SUBSYSTEM_GETTER_INLINE (UHttpNetworkSystem)
Deinitialize()
void UHttpNetworkSystem::Deinitialize () override virtual
Initialize()
void UHttpNetworkSystem::Initialize (FSubsystemCollectionBase & Collection) override virtual
RequestHealth()
void UHttpNetworkSystem::RequestHealth (FResponseHealthDelegate InDelegate)
References Get, NetworkConfig::GetFullUrl(), RequestAPI::Health, NETWORK_GET, and FResponseHealth::SetFromHttpResponse().
RequestHelpChat()
void UHttpNetworkSystem::RequestHelpChat (const FRequestHelpChat & RequestData, FResponseHelpChatDelegate InDelegate)
References NetworkConfig::GetFullUrl(), RequestAPI::HelpChat, NETWORK_LOG, NETWORK_POST, Post, and FResponseHelpChat::SetFromHttpResponse().
The documentation for this class was generated from the following files:
Source/LatteLibrary/Network/Public/UHttpNetworkSystem.h
Source/LatteLibrary/Network/Private/UHttpNetworkSystem.cpp