YiSan Project Documentation: UGameDataManager Class Reference
UGameDataManager Class Reference
#include <UGameDataManager.h>
Public Member Functions
DEFINE_SUBSYSTEM_GETTER_INLINE (UGameDataManager)
UGameDataManager ()
virtual void Initialize (FSubsystemCollectionBase &Collection) override
virtual void Deinitialize () override
void ReloadMasterData ()
bool GetHitStopData (EDamageType Type, UPARAM(ref) FHitStopData &Out) const
float GetHitStopDelayTime (EDamageType Type) const
bool GetKnockbackData (EDamageType Type, FKnockbackData &Out) const
bool GetCharacterInfoData (ECharacterType Type, FCharacterInfoData &Out) const
bool GetCharacterAssetData (ECharacterType Type, FCharacterAssetData &Out) const
Public Attributes
TSoftObjectPtr< UDataTable > HitStopTable
TSoftObjectPtr< UDataTable > KnockbackTable
TSoftObjectPtr< UDataTable > CharacterInfoTable
TSoftObjectPtr< UDataTable > CharacterAssetTable
Constructor & Destructor Documentation
UGameDataManager()
UGameDataManager::UGameDataManager ()
References CHARACTERASSET_PATH, CharacterAssetTable, CHARACTERINFO_PATH, CharacterInfoTable, HITSTOP_PATH, HitStopTable, KNOCKBACK_PATH, KnockbackTable, and FComponentHelper::LoadAsset().
Member Function Documentation
DEFINE_SUBSYSTEM_GETTER_INLINE()
UGameDataManager::DEFINE_SUBSYSTEM_GETTER_INLINE (UGameDataManager)
Deinitialize()
void UGameDataManager::Deinitialize () override virtual
GetCharacterAssetData()
bool UGameDataManager::GetCharacterAssetData (ECharacterType Type, FCharacterAssetData & Out) const
References PRINTLOG.
GetCharacterInfoData()
bool UGameDataManager::GetCharacterInfoData (ECharacterType Type, FCharacterInfoData & Out) const
References PRINTLOG.
GetHitStopData()
bool UGameDataManager::GetHitStopData (EDamageType Type, UPARAM(ref) FHitStopData & Out) const
References PRINTLOG.
GetHitStopDelayTime()
float UGameDataManager::GetHitStopDelayTime (EDamageType Type) const
GetKnockbackData()
bool UGameDataManager::GetKnockbackData (EDamageType Type, FKnockbackData & Out) const
References PRINTLOG.
Initialize()
void UGameDataManager::Initialize (FSubsystemCollectionBase & Collection) override virtual
References ReloadMasterData().
ReloadMasterData()
void UGameDataManager::ReloadMasterData ()
Referenced by Initialize().
Member Data Documentation
CharacterAssetTable
TSoftObjectPtr<UDataTable> UGameDataManager::CharacterAssetTable
Referenced by UGameDataManager().
CharacterInfoTable
TSoftObjectPtr<UDataTable> UGameDataManager::CharacterInfoTable
Referenced by UGameDataManager().
HitStopTable
TSoftObjectPtr<UDataTable> UGameDataManager::HitStopTable
Referenced by UGameDataManager().
KnockbackTable
TSoftObjectPtr<UDataTable> UGameDataManager::KnockbackTable
Referenced by UGameDataManager().
The documentation for this class was generated from the following files:
Source/LatteLibrary/Manager/Public/UGameDataManager.h
Source/LatteLibrary/Manager/Private/UGameDataManager.cpp