YiSan Project Documentation: UGameVFXManager Class Reference
UGameVFXManager Class Reference
#include <UGameVFXManager.h>
Public Member Functions
DEFINE_SUBSYSTEM_GETTER_INLINE (UGameVFXManager)
UGameVFXManager ()
virtual void Initialize (FSubsystemCollectionBase &Collection) override
bool GetVFXData (EVFXType Type, FVFXData &Out) const
void ShowVFX (EVFXType Type, FVector Location, FRotator Rotator, FVector Scale)
Constructor & Destructor Documentation
UGameVFXManager()
UGameVFXManager::UGameVFXManager ()
References FComponentHelper::LoadAsset(), and VFX_DATA_PATH.
Member Function Documentation
DEFINE_SUBSYSTEM_GETTER_INLINE()
UGameVFXManager::DEFINE_SUBSYSTEM_GETTER_INLINE (UGameVFXManager)
GetVFXData()
bool UGameVFXManager::GetVFXData (EVFXType Type, FVFXData & Out) const
References PRINTLOG.
Referenced by ShowVFX().
Initialize()
void UGameVFXManager::Initialize (FSubsystemCollectionBase & Collection) override virtual
ShowVFX()
void UGameVFXManager::ShowVFX (EVFXType Type, FVector Location, FRotator Rotator, FVector Scale)
References GetVFXData(), FVFXData::LocationOffset, FVFXData::RotatorOffset, FVFXData::Scale, and FVFXData::VFXAsset.
The documentation for this class was generated from the following files:
Source/LatteLibrary/Manager/Public/UGameVFXManager.h
Source/LatteLibrary/Manager/Private/UGameVFXManager.cpp