YiSan Project Documentation: APlayerControl Class Reference
APlayerControl Class Reference
#include <APlayerControl.h>
Public Member Functions
APlayerControl ()
Protected Member Functions
virtual void BeginPlay () override
virtual void SetupInputComponent () override
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_Move
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_Look
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_AltitudeUp
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_AltitudeDown
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_Jump
UPROPERTY (EditDefaultsOnly, Category="Input") TObjectPtr< class UInputAction > IA_Landing
void OnMove (const FInputActionValue &Value)
void OnLook (const FInputActionValue &Value)
void OnAltitudeUp (const FInputActionValue &Value)
void OnAltitudeDown (const FInputActionValue &Value)
void OnAltitudeReleased (const FInputActionValue &Value)
void OnJump (const FInputActionValue &Value)
void OnLanding (const FInputActionValue &Value)
Protected Attributes
TObjectPtr< class UInputMappingContext > IMC_Default
Constructor & Destructor Documentation
APlayerControl()
APlayerControl::APlayerControl ()
References IA_ALTITUDE_DOWN_PATH, IA_ALTITUDE_UP_PATH, IA_JUMP_PATH, IA_LANDING_PATH, IA_LOOK_PATH, IA_MOVE_PATH, IMC_Default, IMC_DEFAULT_PATH, and FComponentHelper::LoadAsset().
Member Function Documentation
BeginPlay()
void APlayerControl::BeginPlay () override protected virtual
References IMC_Default.
OnAltitudeDown()
void APlayerControl::OnAltitudeDown (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnAltitudeReleased()
void APlayerControl::OnAltitudeReleased (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnAltitudeUp()
void APlayerControl::OnAltitudeUp (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnJump()
void APlayerControl::OnJump (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnLanding()
void APlayerControl::OnLanding (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnLook()
void APlayerControl::OnLook (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
OnMove()
void APlayerControl::OnMove (const FInputActionValue & Value) protected
Referenced by SetupInputComponent().
SetupInputComponent()
void APlayerControl::SetupInputComponent () override protected virtual
References OnAltitudeDown(), OnAltitudeReleased(), OnAltitudeUp(), OnJump(), OnLanding(), OnLook(), and OnMove().
UPROPERTY() [1/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
UPROPERTY() [2/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
UPROPERTY() [3/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
UPROPERTY() [4/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
UPROPERTY() [5/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
UPROPERTY() [6/6]
APlayerControl::UPROPERTY (EditDefaultsOnly , Category = "Input") protected
Member Data Documentation
IMC_Default
TObjectPtr<class UInputMappingContext> APlayerControl::IMC_Default protected
Referenced by APlayerControl(), and BeginPlay().
The documentation for this class was generated from the following files:
Source/LatteLibrary/Character/Public/APlayerControl.h
Source/LatteLibrary/Character/Private/APlayerControl.cpp