YiSan Project Documentation: ANetworkTesterActor Class Reference
ANetworkTesterActor Class Reference
#include <ANetworkTesterActor.h>
Public Member Functions
ANetworkTesterActor ()
Protected Member Functions
void RequestHealth ()
void OnResponseHealth (FResponseHealth &ResponseData, bool bWasSuccessful)
FORCEINLINE void BP_RequestHelpChat ()
void RequestHelpChat (const FString InQuestion)
void OnResponseHelpChat (FResponseHelpChat &ResponseData, bool bWasSuccessful)
Constructor & Destructor Documentation
ANetworkTesterActor()
ANetworkTesterActor::ANetworkTesterActor ()
Member Function Documentation
BP_RequestHelpChat()
FORCEINLINE void ANetworkTesterActor::BP_RequestHelpChat () inline protected
OnResponseHealth()
void ANetworkTesterActor::OnResponseHealth (FResponseHealth & ResponseData, bool bWasSuccessful) protected
References FResponseHealth::PrintData(), and PRINTLOG.
Referenced by RequestHealth().
OnResponseHelpChat()
void ANetworkTesterActor::OnResponseHelpChat (FResponseHelpChat & ResponseData, bool bWasSuccessful) protected
References FResponseHelpChat::PrintData(), and PRINTLOG.
Referenced by RequestHelpChat().
RequestHealth()
void ANetworkTesterActor::RequestHealth () protected
References OnResponseHealth(), and PRINTLOG.
RequestHelpChat()
void ANetworkTesterActor::RequestHelpChat (const FString InQuestion) protected
References OnResponseHelpChat(), PRINTLOG, and FRequestHelpChat::question.
The documentation for this class was generated from the following files:
Source/LatteLibrary/Network/Public/ANetworkTesterActor.h
Source/LatteLibrary/Network/Private/ANetworkTesterActor.cpp