YiSan Project Documentation: UDelayTaskManager Class Reference
UDelayTaskManager Class Reference
#include <UDelayTaskManager.h>
Public Member Functions
DEFINE_SUBSYSTEM_GETTER_INLINE (UDelayTaskManager)
virtual void Initialize (FSubsystemCollectionBase &Collection) override
virtual void Deinitialize () override
FDelayHandle DelayCallBack (UObject *Owner, float Seconds, FDelayCallback Callback)
FDelayHandle Delay (UObject *Owner, float Seconds, TFunction< void()> Action)
FDelayHandle NextTick (UObject *Owner, TFunction< void()> Action)
bool Cancel (const FDelayHandle &Handle)
void CancelAll (UObject *Owner)
Member Function Documentation
Cancel()
bool UDelayTaskManager::Cancel (const FDelayHandle & Handle)
References FDelayHandle::IsValid(), and FDelayHandle::SeqIndex.
CancelAll()
void UDelayTaskManager::CancelAll (UObject * Owner)
DEFINE_SUBSYSTEM_GETTER_INLINE()
UDelayTaskManager::DEFINE_SUBSYSTEM_GETTER_INLINE (UDelayTaskManager)
Deinitialize()
void UDelayTaskManager::Deinitialize () override virtual
Delay()
FDelayHandle UDelayTaskManager::Delay (UObject * Owner, float Seconds, TFunction< void()> Action)
References FDelayHandle::SeqIndex.
Referenced by DelayCallBack().
DelayCallBack()
FDelayHandle UDelayTaskManager::DelayCallBack (UObject * Owner, float Seconds, FDelayCallback Callback)
References Delay().
Initialize()
void UDelayTaskManager::Initialize (FSubsystemCollectionBase & Collection) override virtual
NextTick()
FDelayHandle UDelayTaskManager::NextTick (UObject * Owner, TFunction< void()> Action)
References FDelayHandle::SeqIndex.
The documentation for this class was generated from the following files:
Source/LatteLibrary/Manager/Public/UDelayTaskManager.h
Source/LatteLibrary/Manager/Private/UDelayTaskManager.cpp