YiSan Project Documentation: FComponentHelper Struct Reference
FComponentHelper Struct Reference
#include <FComponentHelper.h>
Static Public Member Functions
template<typename T >
static T * LoadAsset (const TCHAR *Path)
template<typename T >
static TSubclassOf< T > LoadClass (const TCHAR *Path)
template<typename T >
static T * FindComponentByName (AActor *Owner, const FName &ComponentName)
template<typename T >
static T * FindComponentByNameRecursive (AActor *Owner, const FName &ComponentName)
Member Function Documentation
FindComponentByName()
template<typename T > static T * FComponentHelper::FindComponentByName (AActor * Owner, const FName & ComponentName) inline static
FindComponentByNameRecursive()
template<typename T > static T * FComponentHelper::FindComponentByNameRecursive (AActor * Owner, const FName & ComponentName) inline static
LoadAsset()
template<typename T > static T * FComponentHelper::LoadAsset (const TCHAR * Path) inline static
Referenced by APlayerControl::APlayerControl(), UGameDataManager::UGameDataManager(), UGameSoundManager::UGameSoundManager(), and UGameVFXManager::UGameVFXManager().
LoadClass()
template<typename T > static TSubclassOf< T > FComponentHelper::LoadClass (const TCHAR * Path) inline static
The documentation for this struct was generated from the following file:
Source/CoffeeLibrary/Shared/Public/FComponentHelper.h