YiSan Project Documentation: FEaseHelper Struct Reference
FEaseHelper Struct Reference
#include <FEaseHelper.h>
Static Public Member Functions
static float Ease (float Alpha, EEaseType Type)
Member Function Documentation
Ease()
static float FEaseHelper::Ease (float Alpha, EEaseType Type) inline static
References Ease().
Referenced by ApplyEase(), Ease(), FEaseFloatTrack::Update(), FEaseVectorTrack::Update(), and FEaseRotatorTrack::Update().
The documentation for this struct was generated from the following file:
Source/CoffeeLibrary/Shared/Public/FEaseHelper.h