name: Generate Doxygen Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Download Doxygen Awesome CSS
      run: |-
        wget https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
        mkdir -p docs/html
        mv doxygen-awesome.css docs/html/

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: Doxygen-Documentation
        path: docs/html
